#!/bin/bash
DIR=$(pwd)			


if [ "$1" == "clean" ] 
then
	
	echo "Clean up.."
	rm -rfv Generator/build/*
	rm -rfv Memory_Manager/build/*

elif [ "$#" -eq 6 ]
then

	if [ "$2" -lt "0" ] ||  [ "$2" -gt  "100" ]
	then
		echo "Missmatch Inputs"
	else
		echo "Running project.."

		echo "CMake Building for Generator.."
		cd Generator
		cd build
		cmake ..
		echo "CMake Build done"
		echo "Build project..."
		make
		echo "Build done..."

		cd ../../

		echo "CMake Building for Memory Manager.."
		cd Memory_Manager
		cd build
		cmake ..
		echo "CMake Build done"
		echo "Build project..."
		make
		echo "Build done..."
		gnome-terminal --window-with-profile=Bash -e 'bash -c "./MemoryManager '$6' '$1' ; read"'
		

		cd ../../
		cd Generator
		cd build
		./Generator $1 $2 $3 $4 $5 $6
	fi

else
	echo "Missing arguments.."
fi


